"""
Pydantic Models for Field Portal API — 9-Step Submission Flow

These models define every request/response payload for the React SPA backend.
They also serve as the OpenAPI spec (auto-generated by FastAPI) that a future
Copilot agent plugin will consume.

Flow Steps:
  1. Submit Issue       → IssueSubmission / QualityReviewResponse
  2. Quality Review     → (uses QualityReviewResponse from step 1)
  3. Context Analysis   → AnalysisResponse
  4. User Correction    → CorrectionRequest / CorrectionResponse
  5. Resource Search    → SearchResponse (Learn docs, TFT features, guidance)
  5b. Feature Toggle   → FeatureSelectionRequest / FeatureSelectionResponse
  6. UAT Input          → UATInputRequest
  7. Related UAT Search → RelatedUATsResponse
  8. UAT Toggle         → UATSelectionRequest / UATSelectionResponse
  9. Create UAT         → UATCreateRequest / UATCreatedResponse
"""

from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from datetime import datetime
from enum import Enum


# ============================================================================
# Enums
# ============================================================================

class IssueCategory(str, Enum):
    technical_support = "technical_support"
    feature_request = "feature_request"
    cost_billing = "cost_billing"
    capacity = "capacity"
    aoai_capacity = "aoai_capacity"
    service_request = "service_request"
    information = "information"
    general = "general"


class IntentType(str, Enum):
    escalation = "escalation"
    information = "information"
    action_required = "action_required"
    consultation = "consultation"
    feature_request = "feature_request"
    general = "general"


class BusinessImpact(str, Enum):
    low = "low"
    medium = "medium"
    high = "high"
    critical = "critical"


class FlowStep(str, Enum):
    """Tracks which step in the 9-step flow the session is on."""
    submission = "submission"
    quality_review = "quality_review"
    analysis = "analysis"
    correction = "correction"
    search = "search"
    uat_input = "uat_input"
    related_uats = "related_uats"
    uat_selection = "uat_selection"
    uat_created = "uat_created"


# ============================================================================
# Step 1-2: Issue Submission + Quality Review
# ============================================================================

class IssueSubmission(BaseModel):
    """Step 1: User submits an issue."""
    title: str = Field(..., min_length=1, description="Issue title")
    description: str = Field(..., min_length=1, description="Customer scenario / description")
    impact: str = Field("", description="Business impact statement (recommended)")


class QualityIssue(BaseModel):
    """A single quality issue found in the submission."""
    field: str = Field(..., description="Which field has the issue (title/description/impact)")
    severity: str = Field(..., description="critical/warning/info")
    message: str = Field(..., description="Human-readable issue description")


class DimensionScore(BaseModel):
    """Score for one quality dimension from AI evaluation."""
    score: int = Field(0, ge=0, le=25, description="Dimension score 0-25")
    reason: str = Field("", description="One-sentence justification")


class QualityDimensions(BaseModel):
    """Breakdown of AI quality evaluation across four dimensions."""
    title_clarity: DimensionScore = Field(default_factory=DimensionScore)
    description_quality: DimensionScore = Field(default_factory=DimensionScore)
    business_impact: DimensionScore = Field(default_factory=DimensionScore)
    actionability: DimensionScore = Field(default_factory=DimensionScore)


class QualityReviewResponse(BaseModel):
    """Step 2: Quality review results."""
    session_id: str = Field(..., description="Session ID for this submission flow")
    score: int = Field(..., ge=0, le=100, description="Completeness score 0-100")
    is_complete: bool = Field(..., description="True if score >= block threshold")
    needs_improvement: bool = Field(..., description="True if score < warn threshold")
    blocked: bool = Field(..., description="True if score < block threshold (cannot proceed)")
    issues: List[QualityIssue] = Field(default_factory=list)
    suggestions: List[str] = Field(default_factory=list)
    garbage_detected: bool = Field(False, description="True if gibberish/random input detected")
    original_input: IssueSubmission
    ai_evaluation: bool = Field(False, description="True if scored by AI, False if rules fallback")
    dimensions: Optional[QualityDimensions] = Field(None, description="AI dimension breakdown (null if rules fallback)")


# ============================================================================
# Step 3: Context Analysis
# ============================================================================

class DomainEntities(BaseModel):
    """Detected domain entities from analysis."""
    azure_services: List[str] = Field(default_factory=list)
    technologies: List[str] = Field(default_factory=list)
    regions: List[str] = Field(default_factory=list)


class ContextAnalysis(BaseModel):
    """AI analysis results for the submitted issue."""
    category: str
    category_display: str = ""
    intent: str
    intent_display: str = ""
    confidence: float = Field(..., ge=0.0, le=1.0)
    business_impact: str = ""
    business_impact_display: str = ""
    technical_complexity: str = ""
    urgency_level: str = ""
    key_concepts: List[str] = Field(default_factory=list)
    semantic_keywords: List[str] = Field(default_factory=list)
    domain_entities: DomainEntities = Field(default_factory=DomainEntities)
    context_summary: str = ""
    reasoning: Any = ""  # str or dict depending on source
    source: str = ""  # 'ai' | 'pattern' | 'hybrid'
    ai_available: bool = True
    ai_error: Optional[str] = None


class AnalysisResponse(BaseModel):
    """Step 3: Full analysis response."""
    session_id: str
    original_input: IssueSubmission
    analysis: ContextAnalysis
    timestamp: str = Field(default_factory=lambda: datetime.utcnow().isoformat())


# ============================================================================
# Step 4: Correction
# ============================================================================

class CorrectionRequest(BaseModel):
    """Step 4: User submits corrections to AI classification."""
    session_id: str
    correct_category: Optional[str] = None
    correct_intent: Optional[str] = None
    correct_business_impact: Optional[str] = None
    correct_technical_complexity: Optional[str] = None
    correct_urgency_level: Optional[str] = None
    correction_notes: str = ""
    action: str = Field(..., description="'reanalyze' | 'save_corrections' | 'approve' | 'reject'")


class CorrectionResponse(BaseModel):
    """Step 4: Correction result."""
    session_id: str
    action: str
    updated_analysis: Optional[ContextAnalysis] = None
    corrections_applied: Dict[str, str] = Field(default_factory=dict)
    message: str = ""


# ============================================================================
# Step 5: Search Results
# ============================================================================

class LearnDoc(BaseModel):
    """A Microsoft Learn documentation result."""
    title: str = ""
    url: str = ""
    description: str = ""
    score: float = 0.0


class TFTFeature(BaseModel):
    """A TFT Feature from ADO."""
    id: int
    title: str
    url: str = ""
    similarity: float = 0.0
    state: str = ""
    area_path: str = ""


class CategoryGuidance(BaseModel):
    """Category-specific guidance for the user."""
    title: str
    variant: str = "info"  # info / warning / danger
    items: List[str] = Field(default_factory=list)
    links: Dict[str, str] = Field(default_factory=dict)  # label → URL


class SearchResponse(BaseModel):
    """Step 5: Search results."""
    session_id: str
    learn_docs: List[LearnDoc] = Field(default_factory=list)
    similar_products: List[Dict[str, Any]] = Field(default_factory=list)
    regional_options: List[Dict[str, Any]] = Field(default_factory=list)
    capacity_guidance: Optional[Dict[str, Any]] = None
    retirement_info: Optional[Dict[str, Any]] = None
    tft_features: List[TFTFeature] = Field(default_factory=list)
    category_guidance: Optional[CategoryGuidance] = None
    search_metadata: Dict[str, Any] = Field(default_factory=dict)


# ============================================================================
# Step 5b: TFT Feature selection
# ============================================================================

class FeatureSelectionRequest(BaseModel):
    """Toggle a TFT feature selection."""
    session_id: str
    feature_id: int


class FeatureSelectionResponse(BaseModel):
    """Feature selection result."""
    session_id: str
    selected_features: List[int] = Field(default_factory=list)
    message: str = ""


# ============================================================================
# Step 6: UAT Input
# ============================================================================

class UATInputRequest(BaseModel):
    """Step 6: Opportunity/Milestone IDs."""
    session_id: str
    opportunity_id: str = ""
    milestone_id: str = ""


# ============================================================================
# Step 7-8: Related UATs
# ============================================================================

class RelatedUAT(BaseModel):
    """A similar UAT work item from ADO."""
    id: int
    title: str
    url: str = ""
    similarity: float = 0.0
    state: str = ""
    created_date: str = ""
    assigned_to: str = ""


class RelatedUATsResponse(BaseModel):
    """Step 7: Related UAT search results."""
    session_id: str
    related_uats: List[RelatedUAT] = Field(default_factory=list)
    total_found: int = 0
    search_error: Optional[str] = None


class UATSelectionRequest(BaseModel):
    """Step 8: Toggle a related UAT selection."""
    session_id: str
    uat_id: int


class UATSelectionResponse(BaseModel):
    """Step 8: UAT selection result."""
    session_id: str
    selected_uats: List[int] = Field(default_factory=list)
    message: str = ""


# ============================================================================
# Step 9: UAT Creation
# ============================================================================

class UATCreateRequest(BaseModel):
    """Step 9: Create UAT work item."""
    session_id: str


class LinkedUAT(BaseModel):
    """A linked UAT on the created page (id + title + url)."""
    id: int
    title: str = ""
    url: str = ""


class UATCreatedResponse(BaseModel):
    """Step 9: Created UAT details."""
    session_id: str
    work_item_id: int
    work_item_url: str
    work_item_title: str
    work_item_state: str = "In Progress"
    assigned_to: str = ""
    opportunity_id: str = ""
    milestone_id: str = ""
    selected_features: List[TFTFeature] = Field(default_factory=list)
    selected_uats: List[LinkedUAT] = Field(default_factory=list)


# ============================================================================
# Session / Flow State
# ============================================================================

class SessionState(BaseModel):
    """Complete state of a field submission flow session."""
    session_id: str
    current_step: FlowStep = FlowStep.submission
    created_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())

    # Step 1-2
    original_input: Optional[IssueSubmission] = None
    quality_score: Optional[int] = None

    # Step 3-4
    analysis: Optional[ContextAnalysis] = None
    corrections_applied: Dict[str, str] = Field(default_factory=dict)
    is_reanalyzed: bool = False

    # Step 5
    search_results: Optional[Dict[str, Any]] = None
    selected_features: List[int] = Field(default_factory=list)

    # Step 6
    opportunity_id: str = ""
    milestone_id: str = ""

    # Step 7-8
    related_uats: List[Dict[str, Any]] = Field(default_factory=list)
    selected_uats: List[int] = Field(default_factory=list)

    # Step 9
    work_item_id: Optional[int] = None
    work_item_url: Optional[str] = None


# ============================================================================
# Health / Status
# ============================================================================

class HealthResponse(BaseModel):
    """API health check response."""
    status: str = "healthy"
    version: str = "1.0.0"
    gateway_reachable: bool = False
    active_sessions: int = 0
    timestamp: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
